### ISSUE TITLE
bash train.sh get an error

### ISSUE THREAD

**Issue by sunzhe09** [yuhaoliu7456/Diff-Plugin#1]
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/notebook/code/personal/80239864/Diff-Plugin/train.py:430 in <module>                       │
│                                                                                                  │
│   427 if __name__ == "__main__":                                                                 │
│   428 │   args = parse_args()                                                                    │
│   429 │                                                                                          │
│ ❱ 430 │   main(args)                                                                             │
│   431                                                                                            │
│                                                                                                  │
│ /home/notebook/code/personal/80239864/Diff-Plugin/train.py:160 in main                           │
│                                                                                                  │
│   157 │   backup_unet.config.down_block_types = args.down_block_types                            │
│   158 │   backup_unet.config.block_out_channels = args.block_out_channels                        │
│   159 │   # -------                                                                              │
│ ❱ 160 │   scb_net = SCBNet.from_unet(backup_unet, load_weights_from_unet=args.load_weights_fro   │
│   161 │                                                                                          │
│   162 │   vae.requires_grad_(False)                                                              │
│   163 │   unet.requires_grad_(False)                                                             │
│                                                                                                  │
│ /home/notebook/code/personal/80239864/Diff-Plugin/modules/SCB.py:192 in from_unet                │
│                                                                                                  │
│   189 │   │   │   │   UNet model which weights are copied to the ControlNet. Note that all con   │
│   190 │   │   │   │   copied where applicable.                                                   │
│   191 │   │   """                                                                                │
│ ❱ 192 │   │   controlnet = cls(                                                                  │
│   193 │   │   │   in_channels=unet.config.in_channels,                                           │
│   194 │   │   │   flip_sin_to_cos=unet.config.flip_sin_to_cos,                                   │
│   195 │   │   │   freq_shift=unet.config.freq_shift,                                             │
│                                                                                                  │
│ /opt/conda/envs/py38/lib/python3.8/site-packages/diffusers/configuration_utils.py:636 in         │
│ inner_init                                                                                       │
│                                                                                                  │
│   633 │   │                                                                                      │
│   634 │   │   new_kwargs = {**config_init_kwargs, **new_kwargs}                                  │
│   635 │   │   getattr(self, "register_to_config")(**new_kwargs)                                  │
│ ❱ 636 │   │   init(self, *args, **init_kwargs)                                                   │
│   637 │                                                                                          │
│   638 │   return inner_init                                                                      │
│   639                                                                                            │
│                                                                                                  │
│ /home/notebook/code/personal/80239864/Diff-Plugin/modules/SCB.py:145 in __init__                 │
│                                                                                                  │
│   142 │   │   │   output_channel = block_out_channels[i]                                         │
│   143 │   │   │   is_final_block = i == len(block_out_channels) - 1                              │
│   144 │   │   │                                                                                  │
│ ❱ 145 │   │   │   down_block = get_down_block(                                                   │
│   146 │   │   │   │   down_block_type,                                                           │
│   147 │   │   │   │   num_layers=layers_per_block,                                               │
│   148 │   │   │   │   in_channels=input_channel,                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: get_down_block() got an unexpected keyword argument 'attn_num_head_channels'

**Comment by sunzhe09** [comment]
update diffusier solved this

**Comment by hongsheng-Z** [comment]
Hi, bro, did you solve this issue? which version of diffusers did you use?

**Comment by Valentinajennie** [comment]
You can download and use diffusers==0.17.0.
