### ISSUE TITLE
Colorization model

### ISSUE THREAD

**Issue by hao-pt** [yuhaoliu7456/Diff-Plugin#10]
Thank you for your great work! Could you give me the pretrained plugin for colorization task?

**Comment by yuhaoliu7456** [comment]
You can try to download the weights from this link: [Colorization model](https://portland-my.sharepoint.com/:f:/g/personal/yuhliu9-c_my_cityu_edu_hk/EuaL7O0vVstGoTLgTM25BF0B9EBncfM9UTYoPUpCXoc81g?e=fr3CES) I am not sure if this model weight is the final one. Please try to email me if that's incorrect.

**Comment by hao-pt** [comment]
Thank you for your quick reply! Btw, could you tell me which dataset you used to train this colorization model?

**Comment by yuhaoliu7456** [comment]
If I remember correctly, the colorization model was originally trained for old photo restoration, and the used dataset is FFHQ.

**Comment by hao-pt** [comment]
Great, thanks again!
