### ISSUE TITLE
Inverse generation

### ISSUE THREAD

**Issue by Jumponthemoon** [yuhaoliu7456/Diff-Plugin#12]
Hi,

Much appreciate your effort in creating this interesting work!

I'm curious about the inverse generation of rain and snow in your paper. Would you please give some hints on how to inverse generate those effect?

**Comment by yuhaoliu7456** [comment]
Thanks for your attention on our work. In our work, we just wanted to verify the ability to conduct various tasks in one framework. For the inverse tasks, such as rain and snow generation, you can trivially inverse the input and the ground truth and train a new plug-in. Hope this information will help you.

**Comment by Jumponthemoon** [comment]
Awesome!
 I'm wondering if you have any pretrianed model for generating snow,rain and haze? It would be fine if even it is not perfect, i would use it just for personal usage.
