### ISSUE TITLE
Demoire dataset

### ISSUE THREAD

**Issue by DYY512** [yuhaoliu7456/Diff-Plugin#13]
Hello. Can I get the LCD Moire dataset from you? There is no way to download it now.

**Comment by yuhaoliu7456** [comment]
Please refer to: https://portland-my.sharepoint.com/:f:/g/personal/yuhliu9-c_my_cityu_edu_hk/EqgURMR8rRNOuQRS2l8Ob1sBEDgQlCFrPI7crfLF-Qn_vA?e=wZ80yJ
