### ISSUE TITLE
requirement文件安装失败

### ISSUE THREAD

**Issue by RRunTian** [yuhaoliu7456/Diff-Plugin#14]
PackagesNotFoundError: The following packages are not available from current channels.一个都安装不成功，你们怎么解决的

**Comment by yuhaoliu7456** [comment]
Can you show me the error?

**Comment by Zerycii** [comment]
![微信图片_20240926150118](https://github.com/user-attachments/assets/32104ed0-9b87-4925-b093-9867b56ba800)

**Comment by Zerycii** [comment]
I also met the same error and  requires the python version>=3.9.
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 1.3.0 Requires-Python >=3.9; 1.4.0b1 Requires-Python >=3.10; 1.4.0b2 Requires-Python >=3.10; 4.6.0 Requires-Python >=3.9; 5.0.0b1 Requires-Python >=3.10; 5.0.0b2 Requires-Python >=3.10; 5.0.0b3 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement install==1.3.5 (from versions: none)
ERROR: No matching distribution found for install==1.3.5

**Comment by gttluck** [comment]
> PackagesNotFoundError: The following packages are not available from current channels.一个都安装不成功，你们怎么解决的

I also meet the same problem

**Comment by yuhaoliu7456** [comment]
How about installing the packages one by one?

**Comment by RRunTian** [comment]
> How about installing the packages one by one?

yes, 使用pip安装就可以了

**Comment by Zerycii** [comment]
only method to install these is one by one
