### ISSUE TITLE
Good Work! Some Questions about LCDMoire Dataset.

### ISSUE THREAD

**Issue by SongYan888** [yuhaoliu7456/Diff-Plugin#15]
The official link of LCDMoire Dataset is invalid. Could you please share the dataset with me? My email :gary_144@outlook.com

**Comment by yuhaoliu7456** [comment]
Please refer to this link: https://portland-my.sharepoint.com/:f:/g/personal/yuhliu9-c_my_cityu_edu_hk/EqgURMR8rRNOuQRS2l8Ob1sBEDgQlCFrPI7crfLF-Qn_vA?e=wZ80yJ

**Comment by SongYan888** [comment]
Thank you very much for sharing!
