### ISSUE TITLE
No result image show

### ISSUE THREAD

**Issue by wly-ai-bj** [yuhaoliu7456/Diff-Plugin#3]
The result image does not show

<img width="1306" alt="image" src="https://github.com/yuhaoliu7456/Diff-Plugin/assets/58155968/488ca43f-d5b6-46b1-bc3e-2d6859b7e5d8">

**Comment by wly-ai-bj** [comment]
> The result image does not show
> 
> <img alt="image" width="1306" src="https://private-user-images.githubusercontent.com/58155968/313550302-488ca43f-d5b6-46b1-bc3e-2d6859b7e5d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzY1MzUsIm5iZiI6MTcxMDczNjIzNSwicGF0aCI6Ii81ODE1NTk2OC8zMTM1NTAzMDItNDg4Y2E0M2YtZDViNi00NmIxLWJjM2UtMmQ2ODU5YjdlNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA0MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZjY2ODI5ODBjYTFhZDM3YzdmOGM5ZDNiOTJiNjIyNWI0MzNjYjA0NjkwMDYzODE2MjkzYWIyYzAwZTFiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AdXU81Lvmvito01DXIPJF5Ke6Ma34ZBtUqmJ-sHsubk">

the info on the terminal is :

![image](https://github.com/yuhaoliu7456/Diff-Plugin/assets/58155968/670fa63c-5393-4d35-b818-0085d2e60dc4)

**Comment by yuhaoliu7456** [comment]
Please try restarting the gradio demo and test again. I've tested it and it runs fine.
