### ISSUE TITLE
how to resume？

### ISSUE THREAD

**Issue by yayoyo66** [yuhaoliu7456/Diff-Plugin#4]
I try to use the --resume_from_checkpoint "savepath/checkpointxxxx", but get errors.

I found that the checkpoints only save the scb_net and tpb_net, but the code related the "--resume_from_checkpoint"  looks like it needs to load the original SD1.4 model pytorch_model.bin. 

I wonder if the resume for train.py is valid?

**Comment by yuhaoliu7456** [comment]
Currently the resume func is not supported. I suggest that you can resume the TPB and the SCB modules separately as the ways of saving their weights are different.
