### ISSUE TITLE
how to train with SDXL

### ISSUE THREAD

**Issue by Jeozhao** [yuhaoliu7456/Diff-Plugin#5]
Great work!
Have you tried different SD models? For example, SD2.0, SDXL, etc. What modifications need to be made to update the SD model?

**Comment by yuhaoliu7456** [comment]
Thanks for your interest. We only tested our model on SD 1.4/1.5. For SD 2.0 and XL (base) , I suggest that you can adjust the dimensions of our model to match  the pre-train UNet and try.
