### ISSUE TITLE
SCB dim problem

### ISSUE THREAD

**Issue by zhaozhaoooo** [yuhaoliu7456/Diff-Plugin#7]
hello! the work is very interesting so i want to reproduce it.
when I train the model, I meet a dim proplem in SCB module.
here is the error code
for downsample_block in self.down_blocks:
            if hasattr(downsample_block, "has_cross_attention") and downsample_block.has_cross_attention:
                sample, res_samples = downsample_block(
                    hidden_states=sample,
                    temb=emb,
                    encoder_hidden_states=encoder_hidden_states,
                    attention_mask=attention_mask,
                    cross_attention_kwargs=cross_attention_kwargs,
                )
            else:
                sample, res_samples = downsample_block(hidden_states=sample, temb=emb)

then the error info is:
/data/***/anaconda3/envs/dewarp/lib/python3.9/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1290, in forward
hidden_states = hidden_states + additional_residuals
RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3

so can you help me solve the problem?

**Comment by zhaozhaoooo** [comment]
ok, i have solved this problem caused by the version of diffusers, thanks

**Comment by yuhaoliu7456** [comment]
Thanks, I will close this issue.

**Comment by jinjin1313** [comment]
> hello! the work is very interesting so i want to reproduce it. when I train the model, I meet a dim proplem in SCB module. here is the error code for downsample_block in self.down_blocks: if hasattr(downsample_block, "has_cross_attention") and downsample_block.has_cross_attention: sample, res_samples = downsample_block( hidden_states=sample, temb=emb, encoder_hidden_states=encoder_hidden_states, attention_mask=attention_mask, cross_attention_kwargs=cross_attention_kwargs, ) else: sample, res_samples = downsample_block(hidden_states=sample, temb=emb)
> 
> then the error info is: /data/***/anaconda3/envs/dewarp/lib/python3.9/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1290, in forward hidden_states = hidden_states + additional_residuals RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3
> 
> so can you help me solve the problem?

@zhaozhaoooo 

> ok, i have solved this problem caused by the version of diffusers, thanks



> ok, i have solved this problem caused by the version of diffusers, 

> ok, i have solved this problem caused by the version of diffusers, thanks

@zhaozhaoooo hello! I meet the same problems. can you tell me the the version of diffusers?

**Comment by jinjin1313** [comment]
> ok, i have solved this problem caused by the version of diffusers, thanks

@zhaozhaoooo hello! i  met the same problem and tried to install diffusers=1.17.0 but failed. can you tell me the version of diffusers?

**Comment by zhaozhaoooo** [comment]
my diffusers version is 0.17.0, not 1.17.0. try it again
