### ISSUE TITLE
about document image

### ISSUE THREAD

**Issue by zhaozhaoooo** [yuhaoliu7456/Diff-Plugin#8]
哈喽，你的工作真的很有意思，目前diffusion的工作真的很有意思，也很有效果，正如论文中所说，你的方法可以让diffusion model控制生成，从而保留原来的图像信息，那么你认为对于文档图像会如何呢？因为文档图像对比自然图像来说，有更多的高频特征，文字都是需要保留的，因此可以对生成空间做更多的约束。我在文本图像恢复的数据上用你的方法训练了一版，真的感觉效果很糟糕。
![Uploading 屏幕截图 2024-05-27 142644.png…]()

**Comment by zhaozhaoooo** [comment]
![Uploading 屏幕截图 2024-05-27 142644.png…]()

**Comment by zhaozhaoooo** [comment]
![屏幕截图 2024-05-27 142644](https://github.com/yuhaoliu7456/Diff-Plugin/assets/149659360/5e207c3c-3da5-421b-bed8-270ba36aeb14)

**Comment by yuhaoliu7456** [comment]
对于文档图像来讲，最大的问题在于VAE是存在信息丢失的。所以训练效果不好是make sense的。But，你这个结果应该是在T step的noisy input吧感觉，看不出来什么信息量的东西主要是。如果可以的话，我建议你提供多一些信息

**Comment by zhaozhaoooo** [comment]
天哪，厉害，找了两天bug发现是缩进问题，所以上面那张图像其实只是去噪了一步之后的结果，所以都是噪声，我改正后的文档图像比这好得多
![屏幕截图 2024-05-30 184521](https://github.com/yuhaoliu7456/Diff-Plugin/assets/149659360/785e0065-4cdd-49f2-8076-a7afd0fe6c9a)
谢谢~

**Comment by zhaozhaoooo** [comment]
另外，您在论文中也说到，将补充特征F_s输入到decoder的最后阶段能最大程度的保留保真度。可是事实上您输入F_s的地方是在这里，这里的话是把补充特征出入的下采样层，这里应该是encoder吧？
![屏幕截图 2024-05-30 184829](https://github.com/yuhaoliu7456/Diff-Plugin/assets/149659360/7b1afa2d-ab4c-416a-b9d5-a5e57c1d200f)

**Comment by yuhaoliu7456** [comment]
Please dive into the function and see how it works. Thx.

**Comment by zhaozhaoooo** [comment]
Sorry, I have reviewed the relevant code and the problem has been resolved. Thank you very much for your answer. I will now close this issue.
