### ISSUE TITLE
snow testset

### ISSUE THREAD

**Issue by zyhrainbow** [yuhaoliu7456/Diff-Plugin#9]
Hi can you provide the testset about the desnow task. I can not download from the website. thx

**Comment by yuhaoliu7456** [comment]
Hi, here is the official dataset link: https://sites.google.com/view/yunfuliu/desnownet. Please try to download it again.

**Comment by zyhrainbow** [comment]
> Hi, here is the official dataset link: https://sites.google.com/view/yunfuliu/desnownet. Please try to download it again.
![image](https://github.com/yuhaoliu7456/Diff-Plugin/assets/49444506/ee4374cc-f6d8-487b-86d5-a094a5070484)
I have no access. Can you send a copy to me?

**Comment by yuhaoliu7456** [comment]
Can you send me an email regarding the desnow dataset?

**Comment by zyhrainbow** [comment]
rainbowow@sjtu.edu.cn, thanks very much

**Comment by Jumponthemoon** [comment]
Hi,
Would you please send me one copy as well?
My email is yohji.qian@gmail.com. Thanks!

**Comment by yuhaoliu7456** [comment]
Please refer to: https://portland-my.sharepoint.com/:f:/g/personal/yuhliu9-c_my_cityu_edu_hk/EqgURMR8rRNOuQRS2l8Ob1sBEDgQlCFrPI7crfLF-Qn_vA?e=wZ80yJ

**Comment by zyhrainbow** [comment]
> Please refer to: https://portland-my.sharepoint.com/:f:/g/personal/yuhliu9-c_my_cityu_edu_hk/EqgURMR8rRNOuQRS2l8Ob1sBEDgQlCFrPI7crfLF-Qn_vA?e=wZ80yJ

Hi, this is not the desnowset.

**Comment by yuhaoliu7456** [comment]
Pls try this one: https://portland-my.sharepoint.com/:f:/g/personal/yuhliu9-c_my_cityu_edu_hk/ElLk8j5XImFOuQsvC0EkyzEBb_yDCyCuhgB0YOaaRbyqsA?e=GkolMn

**Comment by cheng221** [comment]
Hi, could you copy your Snow100K and realistic data for me? I am also unable to download it from the website. My email is jcl.ecnu23@gmail.com. Thanks a lot!
